# Generated by Django 4.0.4 on 2022-05-14 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название статьи', max_length=100, verbose_name='Название')),
                ('summary', models.TextField(blank=True, help_text='Текст статьи', max_length=5000, null=True, verbose_name='Текст')),
                ('description', models.TextField(blank=True, help_text='Дополнительные сведения о статье', max_length=3000, null=True, verbose_name='Дополнительно')),
                ('image', models.ImageField(blank=True, help_text='Основное изображение статьи', null=True, upload_to='', verbose_name='Изображение')),
                ('banner', models.ImageField(blank=True, help_text='Основной баннер статьи', null=True, upload_to='', verbose_name='Баннер')),
                ('for_whom', models.CharField(choices=[('p', 'Авторы проектов'), ('a', 'Все')], default='p', help_text='Кто может видеть статью', max_length=1, verbose_name='Видимость')),
                ('footer_num', models.CharField(default='1', help_text='Номер статьи в футере', max_length=2, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Категорія товарів/послуг', max_length=100, verbose_name='Назва')),
                ('service_or_product', models.CharField(choices=[('s', 'Послуги'), ('p', 'Товари')], default='s', help_text='Категорія чого', max_length=1, verbose_name='Категорія чого')),
                ('image', models.ImageField(help_text='Значок чого', upload_to='', verbose_name='Значок')),
                ('banner', models.ImageField(help_text='Банер категорії', upload_to='', verbose_name='Банер')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Місто у Покровському районі', max_length=200, verbose_name='Місто')),
            ],
            options={
                'verbose_name': 'Місто',
                'verbose_name_plural': 'Місто',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название отдела проекта. Например, "Хлебобулочные изделия"', max_length=100, verbose_name='Отдел')),
                ('banner', models.ImageField(blank=True, help_text='Баннер отдела', null=True, upload_to='', verbose_name='Баннер')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название логотипа', max_length=100, verbose_name='Название')),
                ('image', models.ImageField(blank=True, help_text='Логотип сайта', upload_to='', verbose_name='Логотип сайта')),
            ],
            options={
                'verbose_name': 'Логотип',
                'verbose_name_plural': 'Логотипы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Подкатегория товаров/услуг', max_length=100, verbose_name='Наименование')),
                ('image', models.ImageField(help_text='Значок подкатегории', upload_to='', verbose_name='Значок')),
                ('banner', models.ImageField(help_text='Баннер подкатегории', upload_to='', verbose_name='Баннер')),
                ('category', models.ForeignKey(help_text='Категория для текущей подкатегории', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bboard.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назва вашого проєкту', max_length=100, verbose_name='Назва')),
                ('tagline', models.CharField(blank=True, default='Краще для вас', help_text="Слоган вашого проєкту (необов'язково)", max_length=200, null=True, verbose_name='Слоган')),
                ('summary', models.TextField(blank=True, default='Товар/послуга створена для вас', help_text="Опис товарів/послуг, які пропонуєте (необов'язково)", max_length=3000, null=True, verbose_name='Опис')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Змінено')),
                ('tel', models.CharField(blank=True, help_text='Ваш робочий телефон (якщо хочете, щоб споживачі могли дзвонити вам)', max_length=200, null=True, verbose_name='Телефон')),
                ('banner', models.ImageField(blank=True, help_text="Банер для сторінки вашого проєкту (необов'язково)", null=True, upload_to='', verbose_name='Банер')),
                ('image', models.ImageField(blank=True, help_text="Логотип вашого проєкту (необов'язково)", null=True, upload_to='', verbose_name='Логотип')),
                ('status', models.CharField(blank=True, choices=[('g', 'Gold'), ('s', 'Silver'), ('b', 'Bronze'), ('x', 'Blacklist')], default='s', help_text='Статус', max_length=1, verbose_name='Статус')),
                ('state', models.CharField(blank=True, choices=[('a', 'Active'), ('u', 'Unactive')], default='u', help_text='Стан', max_length=1, verbose_name='Стан')),
                ('prime_places', models.CharField(blank=True, choices=[('0', 'None'), ('1', 'Top-10')], default='0', help_text='Прайм-місце', max_length=1, verbose_name='Прайм-місце')),
                ('city', models.ForeignKey(blank=True, help_text="Місто у Покровському районі, у якому продаєте товари або надаєте послуги (необов'язково)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bboard_projects', to='bboard.city', verbose_name='Місто')),
                ('project_owner', models.ForeignKey(help_text='Автор проєкту', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bboard_projects', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Проєкт',
                'verbose_name_plural': 'Проєкти',
                'ordering': ['name', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название товара или услуги. Например, "Хлеб круглый"', max_length=100, verbose_name='Название')),
                ('summary', models.TextField(blank=True, help_text='Краткое описание товара/услуги (необязательно)', max_length=1000, null=True, verbose_name='Описание')),
                ('description', models.TextField(blank=True, help_text='Дополнительные сведения о товаре/услуге (необязательно)', max_length=3000, null=True, verbose_name='Доп. сведения')),
                ('social_links', models.TextField(blank=True, help_text='Ссылки на соцсети (необязательно)', max_length=300, null=True, verbose_name='Ссылки')),
                ('availability_status', models.CharField(choices=[('y', 'Да'), ('n', 'Нет'), ('o', 'Под заказ / По записи')], default='y', help_text='Выберите, доступен ли товар/услуга. Если выбрать "Нет" - товар/услуга не будет виден покупателям', max_length=1, verbose_name='Наличие')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Укажите цену (необязательно). Если не указать, то будет отображаться, значение "Договорная"', max_digits=8, null=True, verbose_name='Цена')),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, help_text='Укажите новую цену с учетом скидки(необязательно)', max_digits=8, null=True, verbose_name='Новая цена')),
                ('image', models.ImageField(blank=True, help_text='Основное фото продукта (необязательно)', null=True, upload_to='', verbose_name='Фото')),
                ('banner', models.ImageField(blank=True, help_text='Баннер продукта (необязательно)', null=True, upload_to='', verbose_name='Баннер')),
                ('prime_places', models.CharField(blank=True, choices=[('0', 'None'), ('1', 'Popular'), ('3', 'Best'), ('4', 'Top')], default='0', help_text='Статус', max_length=1, verbose_name='Прайм-место')),
                ('category', models.ForeignKey(help_text='Выберите категорию', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bboard.category', verbose_name='Категория')),
                ('department', models.ForeignKey(blank=True, help_text='Выберите отдел вашего проекта', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bboard.department', verbose_name='Отдел')),
                ('project', models.ForeignKey(help_text='Проект', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_products', to='bboard.project', verbose_name='Проект')),
                ('project_owner', models.ForeignKey(help_text='Владелец проекта', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('subcategory', models.ForeignKey(help_text='Выберите подкатегорию', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bboard.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=500, verbose_name='Текст')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bboard.project', verbose_name='Проєкт')),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментарії',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='department',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_departments', to='bboard.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='department',
            name='project_owner',
            field=models.ForeignKey(help_text='Владелец проекта', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название баннера', max_length=100, verbose_name='Название')),
                ('image', models.ImageField(help_text='Изображение баннера', upload_to='', verbose_name='Изображение')),
                ('text_1', models.CharField(blank=True, help_text='Текст №1 баннера', max_length=200, null=True, verbose_name='Текст №1')),
                ('text_2', models.CharField(blank=True, help_text='Текст №2 баннера', max_length=200, null=True, verbose_name='Текст №2')),
                ('text_3', models.CharField(blank=True, help_text='Текст №3 баннера', max_length=200, null=True, verbose_name='Текст №3')),
                ('text_4', models.CharField(blank=True, help_text='Текст №4 баннера', max_length=200, null=True, verbose_name='Текст №4')),
                ('text_5', models.CharField(blank=True, help_text='Текст №5 баннера', max_length=200, null=True, verbose_name='Текст №5')),
                ('state', models.CharField(blank=True, choices=[('a', 'Active'), ('u', 'Unactive')], default='u', help_text='Состояние', max_length=1, verbose_name='Состояние')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('product', models.ForeignKey(blank=True, help_text='Продукт', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_banners', to='bboard.product', verbose_name='Продукт')),
                ('project', models.ForeignKey(blank=True, help_text='Проект', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_banners', to='bboard.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['updated'],
            },
        ),
    ]
