# Generated by Django 4.0.4 on 2022-05-21 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='project_owner',
            new_name='account_owner',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='project_owner',
            new_name='account_owner',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='project',
        ),
        migrations.RemoveField(
            model_name='product',
            name='project',
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назва вашого проєкту', max_length=100, verbose_name='Назва')),
                ('tagline', models.CharField(blank=True, default='Краще для вас', help_text="Слоган вашого проєкту (необов'язково)", max_length=200, null=True, verbose_name='Слоган')),
                ('summary', models.TextField(blank=True, default='Товар/послуга створена для вас', help_text="Опис товарів/послуг, які пропонуєте (необов'язково)", max_length=3000, null=True, verbose_name='Опис')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Змінено')),
                ('tel', models.CharField(blank=True, help_text='Ваш робочий телефон (якщо хочете, щоб споживачі могли дзвонити вам)', max_length=200, null=True, verbose_name='Телефон')),
                ('banner', models.ImageField(blank=True, help_text="Банер для сторінки вашого проєкту (необов'язково)", null=True, upload_to='', verbose_name='Банер')),
                ('image', models.ImageField(blank=True, help_text="Логотип вашого проєкту (необов'язково)", null=True, upload_to='', verbose_name='Логотип')),
                ('status', models.CharField(blank=True, choices=[('g', 'Gold'), ('s', 'Silver'), ('b', 'Bronze'), ('x', 'Blacklist')], default='s', help_text='Статус', max_length=1, verbose_name='Статус')),
                ('state', models.CharField(blank=True, choices=[('a', 'Active'), ('u', 'Unactive')], default='u', help_text='Стан', max_length=1, verbose_name='Стан')),
                ('prime_places', models.CharField(blank=True, choices=[('0', 'None'), ('1', 'Top-10')], default='0', help_text='Прайм-місце', max_length=1, verbose_name='Прайм-місце')),
                ('city', models.ForeignKey(blank=True, help_text="Місто у Покровському районі, у якому продаєте товари або надаєте послуги (необов'язково)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bboard_projects', to='bboard.city', verbose_name='Місто')),
                ('project_owner', models.ForeignKey(help_text='Автор проєкту', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bboard_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Проєкт',
                'verbose_name_plural': 'Проєкти',
                'ordering': ['name', '-created'],
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Проект', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_banners', to='bboard.account', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='product',
            name='account',
            field=models.ForeignKey(help_text='Проект', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_products', to='bboard.account', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='department',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_departments', to='bboard.account', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='message',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bboard.account', verbose_name='Проєкт'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
