# Generated by Django 4.0.4 on 2022-05-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='project_owner',
            new_name='account_owner',
        ),
    ]
