# Generated by Django 4.0.4 on 2022-05-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Основное фото продукта (необязательно)', null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
