# Generated by Django 4.0.4 on 2022-05-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='account_owner',
            new_name='project_owner',
        ),
    ]
