# Generated by Django 4.0.4 on 2022-06-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0008_rename_account_owner_product_project_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название изображения', max_length=100, verbose_name='Название')),
                ('image', models.ImageField(help_text='Изображение', upload_to='', verbose_name='Изображение')),
                ('text_1', models.CharField(blank=True, help_text='Текст №1 изображения', max_length=200, null=True, verbose_name='Текст №1')),
                ('state', models.CharField(blank=True, choices=[('a', 'Active'), ('u', 'Unactive')], default='u', help_text='Состояние', max_length=1, verbose_name='Состояние')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['updated'],
            },
        ),
    ]
