# Generated by Django 4.0.4 on 2022-07-20 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0009_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='products_amount',
            field=models.IntegerField(default=3, help_text='Количество продуктов', null=True, verbose_name='Количество продуктов'),
        ),
        migrations.AlterField(
            model_name='product',
            name='account',
            field=models.ForeignKey(help_text='Проект', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_products', to='bboard.account', verbose_name='Проект'),
        ),
    ]
