# Generated by Django 4.0.4 on 2022-07-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0010_account_products_amount_alter_product_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='departments_amount',
            field=models.IntegerField(default=3, help_text='Количество отделов', null=True, verbose_name='Количество отделов'),
        ),
        migrations.AlterField(
            model_name='account',
            name='products_amount',
            field=models.IntegerField(default=10, help_text='Количество продуктов', null=True, verbose_name='Количество продуктов'),
        ),
    ]
