# Generated by Django 4.0.4 on 2022-07-22 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0011_account_departments_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_departments', to='bboard.account', verbose_name='Проект'),
        ),
    ]
