# Generated by Django 4.0.4 on 2022-07-24 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bboard', '0014_alter_account_banner_alter_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_owner',
            field=models.ForeignKey(help_text='Автор проєкту', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.ForeignKey(blank=True, help_text="Місто, у якому продаєте товари або надаєте послуги (необов'язково)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_accounts', to='bboard.city', verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='account',
            name='departments_amount',
            field=models.IntegerField(default=3, help_text='Максимальна кількість відділів', verbose_name='Кількість відділів'),
        ),
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, help_text="Логотип вашого проєкту (необов'язково)", null=True, upload_to='accounts/<django.db.models.fields.CharField>_<built-in function id>/images', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='account',
            name='products_amount',
            field=models.IntegerField(default=10, help_text='Максимальна кількість продуктів', verbose_name='Кількість продуктів'),
        ),
        migrations.AlterField(
            model_name='account',
            name='summary',
            field=models.TextField(blank=True, default='Товар/послуга створена для вас', help_text="Опис товара/послуги, яку пропонуєте (необов'язково)", max_length=3000, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(help_text='Місто', max_length=200, verbose_name='Місто'),
        ),
    ]
