# Generated by Django 4.0.4 on 2022-07-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0021_alter_account_banner_alter_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='banner',
            field=models.ImageField(blank=True, help_text='Основной баннер статьи', null=True, upload_to='articles/banners/%Y/%m/', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='Основное изображение статьи', null=True, upload_to='articles/images/%Y/%m/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Изображение баннера', upload_to='banners/images/%Y/%m/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='banner',
            field=models.ImageField(help_text='Банер категорії', upload_to='categories/banners/', verbose_name='Банер'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(help_text='Значок чого', upload_to='categories/images/', verbose_name='Значок'),
        ),
        migrations.AlterField(
            model_name='department',
            name='banner',
            field=models.ImageField(blank=True, help_text='Баннер отдела', null=True, upload_to='departments/banners/%Y/%m/', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='Изображение', upload_to='images/images/%Y/%m/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(blank=True, help_text='Логотип сайта', upload_to='logos/images/', verbose_name='Логотип сайта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='banner',
            field=models.ImageField(blank=True, help_text='Баннер продукта (необязательно)', null=True, upload_to='products/banners/%Y/%m/', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Основное фото продукта (необязательно)', null=True, upload_to='products/images/%Y/%m/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='banner',
            field=models.ImageField(help_text='Баннер подкатегории', upload_to='subcategories/banners/', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(help_text='Значок подкатегории', upload_to='subcategories/images/', verbose_name='Значок'),
        ),
    ]
