# Generated by Django 4.0.4 on 2022-07-25 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bboard', '0022_alter_article_banner_alter_article_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['name'], 'verbose_name': 'Стаття', 'verbose_name_plural': 'Статті'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['updated'], 'verbose_name': 'Банер', 'verbose_name_plural': 'Банери'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Відділ', 'verbose_name_plural': 'Відділи'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['updated'], 'verbose_name': 'Світлина', 'verbose_name_plural': 'Світлини'},
        ),
        migrations.AlterModelOptions(
            name='logo',
            options={'ordering': ['name'], 'verbose_name': 'Логотип', 'verbose_name_plural': 'Логотипи'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created',), 'verbose_name': 'Коментар', 'verbose_name_plural': 'Коментарі'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукти'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['name'], 'verbose_name': 'Підкатегорія', 'verbose_name_plural': 'Підкатегорії'},
        ),
        migrations.AlterField(
            model_name='article',
            name='banner',
            field=models.ImageField(blank=True, help_text='Основний банер статті', null=True, upload_to='articles/banners/%Y/%m/', verbose_name='Банер'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, help_text='Додаткові відомості про статтю', max_length=3000, null=True, verbose_name='Додатково'),
        ),
        migrations.AlterField(
            model_name='article',
            name='footer_num',
            field=models.CharField(default='1', help_text='Номер статті у футері', max_length=2, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='article',
            name='for_whom',
            field=models.CharField(choices=[('p', 'Автори проєктів'), ('a', 'Всі')], default='p', help_text='Хто може бачити статтю', max_length=1, verbose_name='Видимість'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='Основна світлина статті', null=True, upload_to='articles/images/%Y/%m/', verbose_name='Світлина'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(help_text='Назва статті', max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, help_text='Текст статті', max_length=5000, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Проєкт', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_banners', to='bboard.account', verbose_name='Проєкт'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Світлина банеру', upload_to='banners/images/%Y/%m/', verbose_name='Світлина'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(help_text='Назва банеру', max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Продукт', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_banners', to='bboard.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='state',
            field=models.CharField(blank=True, choices=[('a', 'Active'), ('u', 'Unactive')], default='u', help_text='Стан', max_length=1, verbose_name='Стан'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_1',
            field=models.CharField(blank=True, help_text='Текст №1 банеру', max_length=200, null=True, verbose_name='Текст №1'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_2',
            field=models.CharField(blank=True, help_text='Текст №2 банеру', max_length=200, null=True, verbose_name='Текст №2'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_3',
            field=models.CharField(blank=True, help_text='Текст №3 банеру', max_length=200, null=True, verbose_name='Текст №3'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_4',
            field=models.CharField(blank=True, help_text='Текст №4 банеру', max_length=200, null=True, verbose_name='Текст №4'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_5',
            field=models.CharField(blank=True, help_text='Текст №5 банеру', max_length=200, null=True, verbose_name='Текст №5'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Змінено'),
        ),
        migrations.AlterField(
            model_name='department',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_departments', to='bboard.account', verbose_name='Проєкт'),
        ),
        migrations.AlterField(
            model_name='department',
            name='account_owner',
            field=models.ForeignKey(help_text='Власник проєкту', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_departments', to=settings.AUTH_USER_MODEL, verbose_name='Власник'),
        ),
        migrations.AlterField(
            model_name='department',
            name='banner',
            field=models.ImageField(blank=True, help_text='Банер відділу', null=True, upload_to='departments/banners/%Y/%m/', verbose_name='Банер'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='Назва відділу проєкту. Наприклад, "Хлібобулочні вироби"', max_length=100, verbose_name='Відділ'),
        ),
        migrations.AlterField(
            model_name='image',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='Світлина', upload_to='images/images/%Y/%m/', verbose_name='Світлина'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(help_text='Назва світлини', max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='image',
            name='state',
            field=models.CharField(blank=True, choices=[('a', 'Active'), ('u', 'Unactive')], default='u', help_text='Стан', max_length=1, verbose_name='Стан'),
        ),
        migrations.AlterField(
            model_name='image',
            name='text_1',
            field=models.CharField(blank=True, help_text='Текст №1 світлини', max_length=200, null=True, verbose_name='Текст №1'),
        ),
        migrations.AlterField(
            model_name='image',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Змінено'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(blank=True, help_text='Логотип сайту', upload_to='logos/images/', verbose_name='Логотип сайту'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='name',
            field=models.CharField(help_text='Назва логотипу', max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='message',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_comments', to='bboard.account', verbose_name='Проєкт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='account',
            field=models.ForeignKey(help_text='Проєкт', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_products', to='bboard.account', verbose_name='Проєкт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability_status',
            field=models.CharField(choices=[('y', 'Да'), ('n', 'Нет'), ('o', 'Під заказ / По запису')], default='y', help_text='Оберіть, чи доступний товар/послуга. Якщо обрати "Ні" - товар/послуга не буде відображатися споживачам', max_length=1, verbose_name='Наявність'),
        ),
        migrations.AlterField(
            model_name='product',
            name='banner',
            field=models.ImageField(blank=True, help_text="Банер продукту (необов'язково)", null=True, upload_to='products/banners/%Y/%m/', verbose_name='Банер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Оберіть категорію', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bboard.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='product',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Оберіть відділ вашого продукту', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bboard.department', verbose_name='Відділ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text="Додаткові відомості про товар/послугу (необов'язково)", max_length=3000, null=True, verbose_name='Додаткові відомості'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text="Основна світлина продукту (необов'язково)", null=True, upload_to='products/images/%Y/%m/', verbose_name='Світлина'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Назва товару чи послуги. Наприклад, "Хліб"', max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Вкажіть нову ціну з урахуванням знижки (необов'язково)", max_digits=8, null=True, verbose_name='Нова ціна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Вкажіть ціну (необов\'язково). Якщо не вказувати, то буде відображатися, значення "Договірна"', max_digits=8, null=True, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prime_places',
            field=models.CharField(blank=True, choices=[('0', 'None'), ('1', 'Popular'), ('3', 'Best'), ('4', 'Top')], default='0', help_text='Статус', max_length=1, verbose_name='Прайм-місце'),
        ),
        migrations.AlterField(
            model_name='product',
            name='project_owner',
            field=models.ForeignKey(help_text='Власник проєкту', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_products', to=settings.AUTH_USER_MODEL, verbose_name='Власник'),
        ),
        migrations.AlterField(
            model_name='product',
            name='social_links',
            field=models.TextField(blank=True, help_text="Посилання на соцмережі (необов'язково)", max_length=300, null=True, verbose_name='Посилання'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(help_text='Оберіть підкатегорію', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bboard.subcategory', verbose_name='Підкатегорія'),
        ),
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(blank=True, help_text="Опис товару/прослуги (необов'язково)", max_length=1000, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Змінено'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='banner',
            field=models.ImageField(help_text='Банер підкатегорії', upload_to='subcategories/banners/', verbose_name='Банер'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(help_text='Категорія для поточної підкатегорії', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_subcategories', to='bboard.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(help_text='Значок підкатегорії', upload_to='subcategories/images/', verbose_name='Значок'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(help_text='Підкатегорія товарів/послуг', max_length=100, verbose_name='Підкатегорія'),
        ),
    ]
