# Generated by Django 4.0.4 on 2022-07-25 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bboard', '0023_alter_article_options_alter_banner_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='account_owner',
            field=models.ForeignKey(help_text='Автор проєкту', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_departments', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='product',
            name='project_owner',
            field=models.ForeignKey(help_text='Автор проєкту', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_products', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
