# Generated by Django 4.0.4 on 2023-02-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0024_alter_department_account_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Місто', 'verbose_name_plural': 'Міста'},
        ),
        migrations.AlterField(
            model_name='account',
            name='summary',
            field=models.TextField(blank=True, default='Товар/послуга створена для вас', help_text="Опис товара/послуги, що пропонуєте (необов'язково)", max_length=3000, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability_status',
            field=models.CharField(choices=[('y', 'Так'), ('n', 'Ні'), ('o', 'Під заказ / За записом')], default='y', help_text='Оберіть, чи доступний товар/послуга. Якщо обрати "Ні" - товар/послуга не буде відображатися споживачам', max_length=1, verbose_name='Наявність'),
        ),
    ]
