# Generated by Django 4.0.4 on 2023-02-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0025_alter_city_options_alter_account_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='social_links',
            field=models.TextField(blank=True, help_text="Посилання на соцмережі (необов'язково). Пиши посилання через пробіл, наприклад: https://www.instagram.com/yevhenchlothar/ https://www.facebook.com/yevhen.chlothar", max_length=300, null=True, verbose_name='Посилання'),
        ),
    ]
